### ISSUE TITLE
what's the input image shape?

### ISSUE THREAD

**Issue by BeyondHeaven** [bubbliiiing/Siamese-pytorch#19]
ValueError: Caught ValueError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dockerdata/ruodai1/Siamese-pytorch/nets/siamese.py", line 30, in forward
    x1, x2 = x
ValueError: not enough values to unpack (expected 2, got 1)

I have this error training on my own data

**Comment by bubbliiiing** [comment]
train_own_data = True may help

**Comment by BeyondHeaven** [comment]
I have set this.
Besides, I try to train it on the omniglot dataset and still have this issue

ls images_background/
 Alphabet_of_the_Magi                         Braille              Hebrew                                       N_Ko
 Anglo-Saxon_Futhorc                         'Burmese_(Myanmar)'  'Inuktitut_(Canadian_Aboriginal_Syllabics)'  'Ojibwe_(Canadian_Aboriginal_Syllabics)'
 Arcadian                                     Cyrillic            'Japanese_(hiragana)'                         Sanskrit
 Armenian                                     Early_Aramaic       'Japanese_(katakana)'                        'Syriac_(Estrangelo)'
'Asomtavruli_(Georgian)'                      Futurama             Korean                                       Tagalog
 Balinese                                     Grantha              Latin                                        Tifinagh
 Bengali                                      Greek               'Malay_(Jawi_-_Arabic)'
'Blackfoot_(Canadian_Aboriginal_Syllabics)'   Gujarati            'Mkhedruli_(Georgian)' 

Traceback (most recent call last):
  File "train.py", line 343, in <module>
    fit_one_epoch(model_train, model, loss, loss_history, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, Epoch, Cuda, fp16, scaler, save_period
, save_dir, local_rank)
  File "/dockerdata/test1/Siamese-pytorch/utils/utils_fit.py", line 35, in fit_one_epoch
    outputs = model_train(images)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dockerdata/test1/Siamese-pytorch/nets/siamese.py", line 30, in forward
    x1, x2 = x
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by BeyondHeaven** [comment]
I check the input shape in function fit_one_epoch().
I think the images tensor should be split to two variables

10:43:17.216028 line        26         with torch.no_grad():
10:43:17.220519 line        27             if cuda:
10:43:17.224917 line        28                 images  = images.cuda(local_rank)
**Modified var:.. images = tensor<(2, 64, 3, 105, 105), float32, cuda:0>**
10:43:17.231189 line        29                 targets = targets.cuda(local_rank)
Modified var:.. targets = tensor<(64, 1), float32, cuda:0>
10:43:17.239563 line        34         optimizer.zero_grad()

**Comment by bubbliiiing** [comment]
What is in your PIP list? I want to see your environment of Python. Many people ask this question, but I don't have it myself
