### ISSUE TITLE
训练Omniglot数据集时出现这个报错，ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by loongscale** [bubbliiiing/Siamese-pytorch#43]
Traceback (most recent call last):
  File "train.py", line 344, in <module>
    fit_one_epoch(model_train, model, loss, loss_history, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, Epoch, Cuda, fp16, scaler, save_period, save_dir, local_rank)
  File "/home/stable/dianxuan/code/Siamese-pytorch/utils/utils_fit.py", line 35, in fit_one_epoch
    outputs = model_train(images)
  File "/home/stable/anaconda3/envs/sia/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/stable/anaconda3/envs/sia/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/stable/anaconda3/envs/sia/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/stable/anaconda3/envs/sia/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/stable/anaconda3/envs/sia/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/stable/anaconda3/envs/sia/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/stable/anaconda3/envs/sia/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/stable/dianxuan/code/Siamese-pytorch/nets/siamese.py", line 31, in forward
    x1, x2 = x
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by bubbliiiing** [comment]
hihi
是开多卡了吗

**Comment by sunnee1314** [comment]
> 嘻嘻是开多卡了吗

请问怎么弄？

**Comment by sunnee1314** [comment]
请问我也有这个问题，应该怎么解决？

**Comment by Aster-ze** [comment]
我也出现这个问题，请问你们怎么解决的？

**Comment by lawliet1777** [comment]
你好 解决了吗

**Comment by PMRS-lab** [comment]
我是直接设置成DDP模式，就解决了
